--- #YAML:1.0
name:               Module-New
version:            0.04
abstract:           creates module/distribution skeleton and more
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::HomeDir:        0.66
    Getopt::Long:         0
    Log::Dump:            0.03
    Path::Extended:       0.10
    String::CamelCase:    0
    Sub::Install:         0
    Test::Classy:         0.04
    Test::More:           0.47
    Test::UseAllModules:  0.09
    Text::MicroTemplate:  0.06
    Time::Piece:          0
    YAML:                 0.60
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
