---
abstract: 'creates module/distribution skeleton and more'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-New
no_index:
  directory:
    - t
    - inc
requires:
  File::HomeDir: 0.66
  Getopt::Long: 0
  Log::Dump: 0.03
  Path::Extended: 0.10
  String::CamelCase: 0
  Sub::Install: 0
  Test::Classy: 0.04
  Test::More: 0.47
  Test::UseAllModules: 0.09
  Text::MicroTemplate: 0.06
  Time::Piece: 0
  YAML::Tiny: 1.51
version: 0.07
